# Nexus Forge Kubernetes Namespace Configuration
apiVersion: v1
kind: Namespace
metadata:
  name: nexus-forge
  labels:
    name: nexus-forge
    environment: production
    app.kubernetes.io/name: nexus-forge
    app.kubernetes.io/managed-by: kubectl
  annotations:
    scheduler.alpha.kubernetes.io/node-selector: "workload=general"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: nexus-forge-quota
  namespace: nexus-forge
spec:
  hard:
    requests.cpu: "100"
    requests.memory: "200Gi"
    requests.storage: "1Ti"
    persistentvolumeclaims: "20"
    services: "50"
    configmaps: "100"
    secrets: "100"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: nexus-forge-limits
  namespace: nexus-forge
spec:
  limits:
  - max:
      cpu: "8"
      memory: "16Gi"
    min:
      cpu: "100m"
      memory: "128Mi"
    default:
      cpu: "1"
      memory: "1Gi"
    defaultRequest:
      cpu: "500m"
      memory: "512Mi"
    type: Container
  - max:
      storage: "100Gi"
    min:
      storage: "1Gi"
    type: PersistentVolumeClaim
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nexus-forge-network-policy
  namespace: nexus-forge
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/part-of: nexus-forge
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: nexus-forge
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: nexus-forge
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: nexus-forge
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
  - to:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 169.254.169.254/32  # Block metadata server
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 5432  # PostgreSQL
    - protocol: TCP
      port: 6379  # Redis